[env]
OUT_DIR = "bindings"

[target.'cfg(target_arch = "x86_64")']
cflags = "-mavx -mavx2 -mfma -mf16c -msse3 -mssse3"
cxxflags = "-mavx -mavx2 -mfma -mf16c -msse3 -mssse3"

[target.'cfg(target_arch = "aarch64")']
cflags = "-mcpu=native -mfpu=neon -mno-unaligned-access -funsafe-math-optimizations"
cxxflags = "-mcpu=native -mfpu=neon -mno-unaligned-access -funsafe-math-optimizations"