[env]
OUT_DIR = "bindings"

[target.x86_64-apple-darwin]
[target.x86_64-pc-windows-msvc]
[target.i686-pc-windows-msvc]
[target.x86_64-unknown-linux-gnu]
[target.x86_64-unknown-linux-musl]
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]