RUN apk add --no-cache gcc
RUN apk add --no-cache g++
RUN apk add --no-cache clang-dev
RUN apk add --no-cache nodejs
RUN apk add --no-cache npm
RUN npm i -g yarn
RUN rustup toolchain install nightly
RUN rustup default nightly